In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('../../clean_data/passenger_waittimes.csv')

In [3]:
df.head()

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0

In [4]:
def calc_PAX_through(row):
    if row[6] == 0:
        return 0
    elif row[5] == 0:
        return row[6]
    else:
        return 5.0*row[6]/row[5]

In [5]:
df['PAX_through'] = df.apply(calc_PAX_through, axis=1)

In [6]:
df.dtypes

dt                       object
CalendarYear              int64
Day                      object
Time                     object
Avg Total Time            int64
Max Total Time            int64
Max # of PAX in Line      int64
PAX_through             float64
dtype: object

In [7]:
df.head()

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0

In [8]:
df[df['Max Total Time'] == 0]

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0
5,2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0,0.0
6,2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0,0.0
7,2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0,0.0
8,2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0,0.0
9,2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0,0.0
10,2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0,0.0
11,2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0,0.0
12,2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0,0.0
13,2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0,0.0
14,2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0,0.0
15,2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0,0.0
16,2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0,0.0
17,2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0,0.0
18,2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0,0.0
19,2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0,0.0
20,2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0,0.0
21,2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0,0.0
22,2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0,0.0
23,2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0,0.0
24,2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0,0.0
25,2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0,0.0
26,2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0,0.0
27,2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0,0.0
28,2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0,0.0
29,2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0,0.0
...,...,...,...,...,...,...,...,...
29245,2017-09-17 10:10:00,2017,2017-09-17,10:10:00,0,0,0,0.0
29246,2017-09-17 10:15:00,2017,2017-09-17,10:15:00,0,0,0,0.0
29247,2017-09-17 10:20:00,2017,2017-09-17,10:20:00,0,0,0,0.0
29248,2017-09-17 10:25:00,2017,2017-09-17,10:25:00,0,0,0,0.0
29249,2017-09-17 10:30:00,2017,2017-09-17,10:30:00,0,0,0,0.0
29250,2017-09-17 10:35:00,2017,2017-09-17,10:35:00,0,0,0,0.0
29251,2017-09-17 10:40:00,2017,2017-09-17,10:40:00,0,0,0,0.0
29252,2017-09-17 10:45:00,2017,2017-09-17,10:45:00,0,0,0,0.0
29253,2017-09-17 10:50:00,2017,2017-09-17,10:50:00,0,0,0,0.0
29254,2017-09-17 10:55:00,2017,2017-09-17,10:55:00,0,0,0,0.0
29255,2017-09-17 11:00:00,2017,2017-09-17,11:00:00,0,0,0,0.0
29256,2017-09-17 11:05:00,2017,2017-09-17,11:05:00,0,0,0,0.0
29257,2017-09-17 11:10:00,2017,2017-09-17,11:10:00,0,0,0,0.0
29258,2017-09-17 11:15:00,2017,2017-09-17,11:15:00,0,0,0,0.0
29259,2017-09-17 11:20:00,2017,2017-09-17,11:20:00,0,0,0,0.0
29260,2017-09-17 11:25:00,2017,2017-09-17,11:25:00,0,0,0,0.0
29261,2017-09-17 11:30:00,2017,2017-09-17,11:30:00,0,0,0,0.0
29262,2017-09-17 11:35:00,2017,2017-09-17,11:35:00,0,0,0,0.0
29263,2017-09-17 11:40:00,2017,2017-09-17,11:40:00,0,0,0,0.0
29264,2017-09-17 11:45:00,2017,2017-09-17,11:45:00,0,0,0,0.0
29265,2017-09-17 11:50:00,2017,2017-09-17,11:50:00,0,0,0,0.0
29266,2017-09-17 11:55:00,2017,2017-09-17,11:55:00,0,0,0,0.0
29267,2017-09-17 12:00:00,2017,2017-09-17,12:00:00,0,0,0,0.0
29268,2017-09-17 12:05:00,2017,2017-09-17,12:05:00,0,0,0,0.0
29711,2017-09-19 01:00:00,2017,2017-09-19,01:00:00,0,0,1,1.0
29721,2017-09-19 01:50:00,2017,2017-09-19,01:50:00,0,0,1,1.0
29780,2017-09-19 06:45:00,2017,2017-09-19,06:45:00,0,0,1,1.0
29791,2017-09-19 07:40:00,2017,2017-09-19,07:40:00,0,0,1,1.0
29792,2017-09-19 07:45:00,2017,2017-09-19,07:45:00,0,0,1,1.0
29918,2017-09-19 18:15:00,2017,2017-09-19,18:15:00,0,0,2,2.0

In [9]:
df['passengers_waiting'] = df['Max # of PAX in Line'] - df['PAX_through']

In [10]:
df.head(400)

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.000000,0.000000
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.000000,0.000000
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.000000,0.000000
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.000000,0.000000
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.000000,0.000000
5,2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0,0.000000,0.000000
6,2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0,0.000000,0.000000
7,2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0,0.000000,0.000000
8,2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0,0.000000,0.000000
9,2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0,0.000000,0.000000
10,2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0,0.000000,0.000000
11,2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0,0.000000,0.000000
12,2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0,0.000000,0.000000
13,2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0,0.000000,0.000000
14,2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0,0.000000,0.000000
15,2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0,0.000000,0.000000
16,2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0,0.000000,0.000000
17,2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0,0.000000,0.000000
18,2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0,0.000000,0.000000
19,2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0,0.000000,0.000000
20,2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0,0.000000,0.000000
21,2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0,0.000000,0.000000
22,2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0,0.000000,0.000000
23,2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0,0.000000,0.000000
24,2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0,0.000000,0.000000
25,2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0,0.000000,0.000000
26,2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0,0.000000,0.000000
27,2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0,0.000000,0.000000
28,2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0,0.000000,0.000000
29,2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
370,2017-06-08 23:05:00,2017,2017-06-08,23:05:00,4,5,26,26.000000,0.000000
371,2017-06-08 23:10:00,2017,2017-06-08,23:10:00,4,4,18,22.500000,-4.500000
372,2017-06-08 23:15:00,2017,2017-06-08,23:15:00,3,4,20,25.000000,-5.000000
373,2017-06-08 23:20:00,2017,2017-06-08,23:20:00,3,3,13,21.666667,-8.666667
374,2017-06-08 23:25:00,2017,2017-06-08,23:25:00,2,2,9,22.500000,-13.500000
375,2017-06-08 23:30:00,2017,2017-06-08,23:30:00,5,7,40,28.571429,11.428571
376,2017-06-08 23:35:00,2017,2017-06-08,23:35:00,5,6,36,30.000000,6.000000
377,2017-06-08 23:40:00,2017,2017-06-08,23:40:00,3,3,13,21.666667,-8.666667
378,2017-06-08 23:45:00,2017,2017-06-08,23:45:00,3,3,16,26.666667,-10.666667
379,2017-06-08 23:50:00,2017,2017-06-08,23:50:00,2,2,9,22.500000,-13.500000
380,2017-06-08 23:55:00,2017,2017-06-08,23:55:00,2,3,11,18.333333,-7.333333
381,2017-06-09 00:00:00,2017,2017-06-09,00:00:00,2,2,7,17.500000,-10.500000
382,2017-06-09 00:05:00,2017,2017-06-09,00:05:00,1,2,7,17.500000,-10.500000
383,2017-06-09 00:10:00,2017,2017-06-09,00:10:00,2,2,7,17.500000,-10.500000
384,2017-06-09 00:15:00,2017,2017-06-09,00:15:00,2,2,7,17.500000,-10.500000
385,2017-06-09 00:20:00,2017,2017-06-09,00:20:00,2,2,8,20.000000,-12.000000
386,2017-06-09 00:25:00,2017,2017-06-09,00:25:00,2,2,8,20.000000,-12.000000
387,2017-06-09 00:30:00,2017,2017-06-09,00:30:00,1,1,5,25.000000,-20.000000
388,2017-06-09 00:35:00,2017,2017-06-09,00:35:00,1,2,6,15.000000,-9.000000
389,2017-06-09 00:40:00,2017,2017-06-09,00:40:00,1,1,5,25.000000,-20.000000
390,2017-06-09 00:45:00,2017,2017-06-09,00:45:00,1,1,5,25.000000,-20.000000
391,2017-06-09 00:50:00,2017,2017-06-09,00:50:00,1,2,6,15.000000,-9.000000
392,2017-06-09 00:55:00,2017,2017-06-09,00:55:00,1,1,5,25.000000,-20.000000
393,2017-06-09 01:00:00,2017,2017-06-09,01:00:00,1,1,5,25.000000,-20.000000
394,2017-06-09 01:05:00,2017,2017-06-09,01:05:00,1,1,5,25.000000,-20.000000
395,2017-06-09 01:10:00,2017,2017-06-09,01:10:00,1,2,7,17.500000,-10.500000
396,2017-06-09 01:15:00,2017,2017-06-09,01:15:00,1,2,6,15.000000,-9.000000
397,2017-06-09 01:20:00,2017,2017-06-09,01:20:00,1,1,4,20.000000,-16.000000
398,2017-06-09 01:25:00,2017,2017-06-09,01:25:00,1,2,6,15.000000,-9.000000
399,2017-06-09 01:30:00,2017,2017-06-09,01:30:00,1,2,6,15.000000,-9.000000

In [11]:
df = df.set_index('dt')

In [12]:
df.head()

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0,0.0
2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0,0.0
2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0,0.0
2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0,0.0
2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0,0.0

In [14]:
df.index = pd.DatetimeIndex(df.index)

In [15]:
df.head()

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0,0.0
2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0,0.0
2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0,0.0
2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0,0.0
2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0,0.0

In [ ]:
# df.dt = pd.to_datetime(df.dt)

In [17]:
df.resample('1H').last()

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:00:00,2017.0,2017-06-07,16:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 17:00:00,2017.0,2017-06-07,17:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 18:00:00,2017.0,2017-06-07,18:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 19:00:00,2017.0,2017-06-07,19:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 20:00:00,2017.0,2017-06-07,20:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 21:00:00,2017.0,2017-06-07,21:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 22:00:00,2017.0,2017-06-07,22:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 23:00:00,2017.0,2017-06-07,23:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 00:00:00,2017.0,2017-06-08,00:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 01:00:00,2017.0,2017-06-08,01:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 02:00:00,2017.0,2017-06-08,02:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 03:00:00,2017.0,2017-06-08,03:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 04:00:00,2017.0,2017-06-08,04:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 05:00:00,2017.0,2017-06-08,05:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 06:00:00,2017.0,2017-06-08,06:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 07:00:00,2017.0,2017-06-08,07:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 08:00:00,2017.0,2017-06-08,08:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 09:00:00,2017.0,2017-06-08,09:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 10:00:00,2017.0,2017-06-08,10:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 11:00:00,2017.0,2017-06-08,11:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 12:00:00,2017.0,2017-06-08,12:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 13:00:00,2017.0,2017-06-08,13:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 14:00:00,2017.0,2017-06-08,14:55:00,9.0,13.0,69.0,26.538462,42.461538
2017-06-08 15:00:00,2017.0,2017-06-08,15:55:00,9.0,10.0,53.0,26.500000,26.500000
2017-06-08 16:00:00,2017.0,2017-06-08,16:55:00,9.0,11.0,62.0,28.181818,33.818182
2017-06-08 17:00:00,2017.0,2017-06-08,17:55:00,15.0,16.0,84.0,26.250000,57.750000
2017-06-08 18:00:00,2017.0,2017-06-08,18:55:00,3.0,6.0,34.0,28.333333,5.666667
2017-06-08 19:00:00,2017.0,2017-06-08,19:55:00,11.0,14.0,78.0,27.857143,50.142857
2017-06-08 20:00:00,2017.0,2017-06-08,20:55:00,11.0,12.0,68.0,28.333333,39.666667
2017-06-08 21:00:00,2017.0,2017-06-08,21:55:00,10.0,12.0,66.0,27.500000,38.500000
...,...,...,...,...,...,...,...,...
2017-09-18 19:00:00,2017.0,2017-09-18,19:55:00,8.0,8.0,48.0,30.000000,18.000000
2017-09-18 20:00:00,2017.0,2017-09-18,20:55:00,11.0,14.0,77.0,27.500000,49.500000
2017-09-18 21:00:00,2017.0,2017-09-18,21:55:00,6.0,7.0,40.0,28.571429,11.428571
2017-09-18 22:00:00,2017.0,2017-09-18,22:55:00,2.0,3.0,15.0,25.000000,-10.000000
2017-09-18 23:00:00,2017.0,2017-09-18,23:55:00,1.0,1.0,5.0,25.000000,-20.000000
2017-09-19 00:00:00,2017.0,2017-09-19,00:55:00,1.0,2.0,4.0,10.000000,-6.000000
2017-09-19 01:00:00,2017.0,2017-09-19,01:55:00,1.0,2.0,3.0,7.500000,-4.500000
2017-09-19 02:00:00,2017.0,2017-09-19,02:55:00,1.0,2.0,3.0,7.500000,-4.500000
2017-09-19 03:00:00,2017.0,2017-09-19,03:55:00,0.0,2.0,3.0,7.500000,-4.500000
2017-09-19 04:00:00,2017.0,2017-09-19,04:55:00,0.0,1.0,2.0,10.000000,-8.000000
2017-09-19 05:00:00,2017.0,2017-09-19,05:55:00,1.0,2.0,4.0,10.000000,-6.000000
2017-09-19 06:00:00,2017.0,2017-09-19,06:55:00,1.0,1.0,2.0,10.000000,-8.000000
2017-09-19 07:00:00,2017.0,2017-09-19,07:55:00,2.0,2.0,4.0,10.000000,-6.000000
2017-09-19 08:00:00,2017.0,2017-09-19,08:55:00,2.0,3.0,7.0,11.666667,-4.666667
2017-09-19 09:00:00,2017.0,2017-09-19,09:55:00,3.0,3.0,13.0,21.666667,-8.666667
2017-09-19 10:00:00,2017.0,2017-09-19,10:55:00,2.0,2.0,6.0,15.000000,-9.000000
2017-09-19 11:00:00,2017.0,2017-09-19,11:55:00,2.0,4.0,21.0,26.250000,-5.250000
2017-09-19 12:00:00,2017.0,2017-09-19,12:55:00,2.0,2.0,9.0,22.500000,-13.500000
2017-09-19 13:00:00,2017.0,2017-09-19,13:55:00,4.0,4.0,22.0,27.500000,-5.500000
2017-09-19 14:00:00,2017.0,2017-09-19,14:55:00,3.0,3.0,14.0,23.333333,-9.333333
2017-09-19 15:00:00,2017.0,2017-09-19,15:55:00,2.0,3.0,10.0,16.666667,-6.666667
2017-09-19 16:00:00,2017.0,2017-09-19,16:55:00,4.0,5.0,25.0,25.000000,0.000000
2017-09-19 17:00:00,2017.0,2017-09-19,17:55:00,11.0,12.0,41.0,17.083333,23.916667
2017-09-19 18:00:00,2017.0,2017-09-19,18:55:00,6.0,7.0,37.0,26.428571,10.571429
2017-09-19 19:00:00,2017.0,2017-09-19,19:55:00,2.0,2.0,7.0,17.500000,-10.500000
2017-09-19 20:00:00,2017.0,2017-09-19,20:55:00,1.0,1.0,5.0,25.000000,-20.000000
2017-09-19 21:00:00,2017.0,2017-09-19,21:55:00,13.0,15.0,79.0,26.333333,52.666667
2017-09-19 22:00:00,2017.0,2017-09-19,22:55:00,0.0,1.0,3.0,15.000000,-12.000000
2017-09-19 23:00:00,2017.0,2017-09-19,23:55:00,2.0,2.0,5.0,12.500000,-7.500000
2017-09-20 00:00:00,2017.0,2017-09-20,00:55:00,1.0,2.0,3.0,7.500000,-4.500000

In [20]:
df[df['passengers_waiting'] < 0] = 0

In [23]:
df[df['passengers_waiting']!=0]

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-08 14:35:00,2017,2017-06-08,14:35:00,5,6,34,28.333333,5.666667
2017-06-08 14:40:00,2017,2017-06-08,14:40:00,6,7,41,29.285714,11.714286
2017-06-08 14:45:00,2017,2017-06-08,14:45:00,7,9,51,28.333333,22.666667
2017-06-08 14:50:00,2017,2017-06-08,14:50:00,9,13,70,26.923077,43.076923
2017-06-08 14:55:00,2017,2017-06-08,14:55:00,9,13,69,26.538462,42.461538
2017-06-08 15:00:00,2017,2017-06-08,15:00:00,11,12,68,28.333333,39.666667
2017-06-08 15:05:00,2017,2017-06-08,15:05:00,9,12,66,27.500000,38.500000
2017-06-08 15:10:00,2017,2017-06-08,15:10:00,9,10,54,27.000000,27.000000
2017-06-08 15:15:00,2017,2017-06-08,15:15:00,9,11,60,27.272727,32.727273
2017-06-08 15:20:00,2017,2017-06-08,15:20:00,8,10,58,29.000000,29.000000
2017-06-08 15:25:00,2017,2017-06-08,15:25:00,10,11,60,27.272727,32.727273
2017-06-08 15:30:00,2017,2017-06-08,15:30:00,9,10,57,28.500000,28.500000
2017-06-08 15:35:00,2017,2017-06-08,15:35:00,10,10,58,29.000000,29.000000
2017-06-08 15:40:00,2017,2017-06-08,15:40:00,8,11,63,28.636364,34.363636
2017-06-08 15:45:00,2017,2017-06-08,15:45:00,9,11,62,28.181818,33.818182
2017-06-08 15:50:00,2017,2017-06-08,15:50:00,11,13,71,27.307692,43.692308
2017-06-08 15:55:00,2017,2017-06-08,15:55:00,9,10,53,26.500000,26.500000
2017-06-08 16:00:00,2017,2017-06-08,16:00:00,9,10,56,28.000000,28.000000
2017-06-08 16:05:00,2017,2017-06-08,16:05:00,8,10,53,26.500000,26.500000
2017-06-08 16:10:00,2017,2017-06-08,16:10:00,10,10,55,27.500000,27.500000
2017-06-08 16:15:00,2017,2017-06-08,16:15:00,9,11,61,27.727273,33.272727
2017-06-08 16:20:00,2017,2017-06-08,16:20:00,11,12,64,26.666667,37.333333
2017-06-08 16:25:00,2017,2017-06-08,16:25:00,10,10,57,28.500000,28.500000
2017-06-08 16:30:00,2017,2017-06-08,16:30:00,11,11,63,28.636364,34.363636
2017-06-08 16:35:00,2017,2017-06-08,16:35:00,11,12,66,27.500000,38.500000
2017-06-08 16:40:00,2017,2017-06-08,16:40:00,11,11,63,28.636364,34.363636
2017-06-08 16:45:00,2017,2017-06-08,16:45:00,13,14,77,27.500000,49.500000
2017-06-08 16:50:00,2017,2017-06-08,16:50:00,11,12,66,27.500000,38.500000
2017-06-08 16:55:00,2017,2017-06-08,16:55:00,9,11,62,28.181818,33.818182
2017-06-08 17:00:00,2017,2017-06-08,17:00:00,12,13,71,27.307692,43.692308
...,...,...,...,...,...,...,...,...
2017-09-19 17:40:00,2017,2017-09-19,17:40:00,11,12,43,17.916667,25.083333
2017-09-19 17:45:00,2017,2017-09-19,17:45:00,8,9,37,20.555556,16.444444
2017-09-19 17:50:00,2017,2017-09-19,17:50:00,11,13,45,17.307692,27.692308
2017-09-19 17:55:00,2017,2017-09-19,17:55:00,11,12,41,17.083333,23.916667
2017-09-19 18:00:00,2017,2017-09-19,18:00:00,7,10,31,15.500000,15.500000
2017-09-19 18:55:00,2017,2017-09-19,18:55:00,6,7,37,26.428571,10.571429
2017-09-19 19:00:00,2017,2017-09-19,19:00:00,7,7,39,27.857143,11.142857
2017-09-19 19:05:00,2017,2017-09-19,19:05:00,5,6,32,26.666667,5.333333
2017-09-19 19:10:00,2017,2017-09-19,19:10:00,7,7,25,17.857143,7.142857
2017-09-19 19:15:00,2017,2017-09-19,19:15:00,8,10,38,19.000000,19.000000
2017-09-19 19:20:00,2017,2017-09-19,19:20:00,9,12,42,17.500000,24.500000
2017-09-19 19:25:00,2017,2017-09-19,19:25:00,7,8,44,27.500000,16.500000
2017-09-19 19:30:00,2017,2017-09-19,19:30:00,8,8,46,28.750000,17.250000
2017-09-19 19:35:00,2017,2017-09-19,19:35:00,6,8,46,28.750000,17.250000
2017-09-19 20:35:00,2017,2017-09-19,20:35:00,6,7,39,27.857143,11.142857
2017-09-19 20:40:00,2017,2017-09-19,20:40:00,5,6,34,28.333333,5.666667
2017-09-19 21:10:00,2017,2017-09-19,21:10:00,4,7,43,30.714286,12.285714
2017-09-19 21:15:00,2017,2017-09-19,21:15:00,6,8,46,28.750000,17.250000
2017-09-19 21:20:00,2017,2017-09-19,21:20:00,7,8,48,30.000000,18.000000
2017-09-19 21:25:00,2017,2017-09-19,21:25:00,7,8,45,28.125000,16.875000
2017-09-19 21:30:00,2017,2017-09-19,21:30:00,10,11,59,26.818182,32.181818
2017-09-19 21:35:00,2017,2017-09-19,21:35:00,10,10,57,28.500000,28.500000
2017-09-19 21:40:00,2017,2017-09-19,21:40:00,7,9,51,28.333333,22.666667
2017-09-19 21:45:00,2017,2017-09-19,21:45:00,7,7,43,30.714286,12.285714
2017-09-19 21:50:00,2017,2017-09-19,21:50:00,10,12,64,26.666667,37.333333
2017-09-19 21:55:00,2017,2017-09-19,21:55:00,13,15,79,26.333333,52.666667
2017-09-19 22:00:00,2017,2017-09-19,22:00:00,13,16,83,25.937500,57.062500
2017-09-19 22:05:00,2017,2017-09-19,22:05:00,14,18,95,26.388889,68.611111
2017-09-19 22:10:00,2017,2017-09-19,22:10:00,8,10,57,28.500000,28.500000
2017-09-19 22:15:00,2017,2017-09-19,22:15:00,7,11,61,27.727273,33.272727