In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:
df = pd.read_csv('../../clean_data/passenger_waittimes.csv')

In [27]:
df.head(400)

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0
5,2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0
6,2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0
7,2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0
8,2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0
9,2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0
10,2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0
11,2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0
12,2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0
13,2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0
14,2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0
15,2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0
16,2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0
17,2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0
18,2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0
19,2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0
20,2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0
21,2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0
22,2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0
23,2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0
24,2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0
25,2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0
26,2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0
27,2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0
28,2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0
29,2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0
...,...,...,...,...,...,...,...
370,2017-06-08 23:05:00,2017,2017-06-08,23:05:00,4,5,26
371,2017-06-08 23:10:00,2017,2017-06-08,23:10:00,4,4,18
372,2017-06-08 23:15:00,2017,2017-06-08,23:15:00,3,4,20
373,2017-06-08 23:20:00,2017,2017-06-08,23:20:00,3,3,13
374,2017-06-08 23:25:00,2017,2017-06-08,23:25:00,2,2,9
375,2017-06-08 23:30:00,2017,2017-06-08,23:30:00,5,7,40
376,2017-06-08 23:35:00,2017,2017-06-08,23:35:00,5,6,36
377,2017-06-08 23:40:00,2017,2017-06-08,23:40:00,3,3,13
378,2017-06-08 23:45:00,2017,2017-06-08,23:45:00,3,3,16
379,2017-06-08 23:50:00,2017,2017-06-08,23:50:00,2,2,9
380,2017-06-08 23:55:00,2017,2017-06-08,23:55:00,2,3,11
381,2017-06-09 00:00:00,2017,2017-06-09,00:00:00,2,2,7
382,2017-06-09 00:05:00,2017,2017-06-09,00:05:00,1,2,7
383,2017-06-09 00:10:00,2017,2017-06-09,00:10:00,2,2,7
384,2017-06-09 00:15:00,2017,2017-06-09,00:15:00,2,2,7
385,2017-06-09 00:20:00,2017,2017-06-09,00:20:00,2,2,8
386,2017-06-09 00:25:00,2017,2017-06-09,00:25:00,2,2,8
387,2017-06-09 00:30:00,2017,2017-06-09,00:30:00,1,1,5
388,2017-06-09 00:35:00,2017,2017-06-09,00:35:00,1,2,6
389,2017-06-09 00:40:00,2017,2017-06-09,00:40:00,1,1,5
390,2017-06-09 00:45:00,2017,2017-06-09,00:45:00,1,1,5
391,2017-06-09 00:50:00,2017,2017-06-09,00:50:00,1,2,6
392,2017-06-09 00:55:00,2017,2017-06-09,00:55:00,1,1,5
393,2017-06-09 01:00:00,2017,2017-06-09,01:00:00,1,1,5
394,2017-06-09 01:05:00,2017,2017-06-09,01:05:00,1,1,5
395,2017-06-09 01:10:00,2017,2017-06-09,01:10:00,1,2,7
396,2017-06-09 01:15:00,2017,2017-06-09,01:15:00,1,2,6
397,2017-06-09 01:20:00,2017,2017-06-09,01:20:00,1,1,4
398,2017-06-09 01:25:00,2017,2017-06-09,01:25:00,1,2,6
399,2017-06-09 01:30:00,2017,2017-06-09,01:30:00,1,2,6

In [28]:
def calc_PAX_through(row):
    if row[6] == 0:
        return 0
    elif row[5] == 0:
        return row[6]
    else:
        return 5.0*row[6]/row[5]

In [29]:
df['PAX_through'] = df.apply(calc_PAX_through, axis=1)

In [30]:
df.dtypes

dt                       object
CalendarYear              int64
Day                      object
Time                     object
Avg Total Time            int64
Max Total Time            int64
Max # of PAX in Line      int64
PAX_through             float64
dtype: object

In [31]:
df.head()

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0

In [32]:
df[df['Max Total Time'] == 0]

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0
5,2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0,0.0
6,2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0,0.0
7,2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0,0.0
8,2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0,0.0
9,2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0,0.0
10,2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0,0.0
11,2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0,0.0
12,2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0,0.0
13,2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0,0.0
14,2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0,0.0
15,2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0,0.0
16,2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0,0.0
17,2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0,0.0
18,2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0,0.0
19,2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0,0.0
20,2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0,0.0
21,2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0,0.0
22,2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0,0.0
23,2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0,0.0
24,2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0,0.0
25,2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0,0.0
26,2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0,0.0
27,2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0,0.0
28,2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0,0.0
29,2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0,0.0
...,...,...,...,...,...,...,...,...
29245,2017-09-17 10:10:00,2017,2017-09-17,10:10:00,0,0,0,0.0
29246,2017-09-17 10:15:00,2017,2017-09-17,10:15:00,0,0,0,0.0
29247,2017-09-17 10:20:00,2017,2017-09-17,10:20:00,0,0,0,0.0
29248,2017-09-17 10:25:00,2017,2017-09-17,10:25:00,0,0,0,0.0
29249,2017-09-17 10:30:00,2017,2017-09-17,10:30:00,0,0,0,0.0
29250,2017-09-17 10:35:00,2017,2017-09-17,10:35:00,0,0,0,0.0
29251,2017-09-17 10:40:00,2017,2017-09-17,10:40:00,0,0,0,0.0
29252,2017-09-17 10:45:00,2017,2017-09-17,10:45:00,0,0,0,0.0
29253,2017-09-17 10:50:00,2017,2017-09-17,10:50:00,0,0,0,0.0
29254,2017-09-17 10:55:00,2017,2017-09-17,10:55:00,0,0,0,0.0
29255,2017-09-17 11:00:00,2017,2017-09-17,11:00:00,0,0,0,0.0
29256,2017-09-17 11:05:00,2017,2017-09-17,11:05:00,0,0,0,0.0
29257,2017-09-17 11:10:00,2017,2017-09-17,11:10:00,0,0,0,0.0
29258,2017-09-17 11:15:00,2017,2017-09-17,11:15:00,0,0,0,0.0
29259,2017-09-17 11:20:00,2017,2017-09-17,11:20:00,0,0,0,0.0
29260,2017-09-17 11:25:00,2017,2017-09-17,11:25:00,0,0,0,0.0
29261,2017-09-17 11:30:00,2017,2017-09-17,11:30:00,0,0,0,0.0
29262,2017-09-17 11:35:00,2017,2017-09-17,11:35:00,0,0,0,0.0
29263,2017-09-17 11:40:00,2017,2017-09-17,11:40:00,0,0,0,0.0
29264,2017-09-17 11:45:00,2017,2017-09-17,11:45:00,0,0,0,0.0
29265,2017-09-17 11:50:00,2017,2017-09-17,11:50:00,0,0,0,0.0
29266,2017-09-17 11:55:00,2017,2017-09-17,11:55:00,0,0,0,0.0
29267,2017-09-17 12:00:00,2017,2017-09-17,12:00:00,0,0,0,0.0
29268,2017-09-17 12:05:00,2017,2017-09-17,12:05:00,0,0,0,0.0
29711,2017-09-19 01:00:00,2017,2017-09-19,01:00:00,0,0,1,1.0
29721,2017-09-19 01:50:00,2017,2017-09-19,01:50:00,0,0,1,1.0
29780,2017-09-19 06:45:00,2017,2017-09-19,06:45:00,0,0,1,1.0
29791,2017-09-19 07:40:00,2017,2017-09-19,07:40:00,0,0,1,1.0
29792,2017-09-19 07:45:00,2017,2017-09-19,07:45:00,0,0,1,1.0
29918,2017-09-19 18:15:00,2017,2017-09-19,18:15:00,0,0,2,2.0

In [33]:
df['passengers_waiting'] = df['Max # of PAX in Line'] - df['PAX_through']

In [34]:
df.head(400)

,dt,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
0,2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.000000,0.000000
1,2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.000000,0.000000
2,2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.000000,0.000000
3,2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.000000,0.000000
4,2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.000000,0.000000
5,2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0,0.000000,0.000000
6,2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0,0.000000,0.000000
7,2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0,0.000000,0.000000
8,2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0,0.000000,0.000000
9,2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0,0.000000,0.000000
10,2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0,0.000000,0.000000
11,2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0,0.000000,0.000000
12,2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0,0.000000,0.000000
13,2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0,0.000000,0.000000
14,2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0,0.000000,0.000000
15,2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0,0.000000,0.000000
16,2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0,0.000000,0.000000
17,2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0,0.000000,0.000000
18,2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0,0.000000,0.000000
19,2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0,0.000000,0.000000
20,2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0,0.000000,0.000000
21,2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0,0.000000,0.000000
22,2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0,0.000000,0.000000
23,2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0,0.000000,0.000000
24,2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0,0.000000,0.000000
25,2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0,0.000000,0.000000
26,2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0,0.000000,0.000000
27,2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0,0.000000,0.000000
28,2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0,0.000000,0.000000
29,2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
370,2017-06-08 23:05:00,2017,2017-06-08,23:05:00,4,5,26,26.000000,0.000000
371,2017-06-08 23:10:00,2017,2017-06-08,23:10:00,4,4,18,22.500000,-4.500000
372,2017-06-08 23:15:00,2017,2017-06-08,23:15:00,3,4,20,25.000000,-5.000000
373,2017-06-08 23:20:00,2017,2017-06-08,23:20:00,3,3,13,21.666667,-8.666667
374,2017-06-08 23:25:00,2017,2017-06-08,23:25:00,2,2,9,22.500000,-13.500000
375,2017-06-08 23:30:00,2017,2017-06-08,23:30:00,5,7,40,28.571429,11.428571
376,2017-06-08 23:35:00,2017,2017-06-08,23:35:00,5,6,36,30.000000,6.000000
377,2017-06-08 23:40:00,2017,2017-06-08,23:40:00,3,3,13,21.666667,-8.666667
378,2017-06-08 23:45:00,2017,2017-06-08,23:45:00,3,3,16,26.666667,-10.666667
379,2017-06-08 23:50:00,2017,2017-06-08,23:50:00,2,2,9,22.500000,-13.500000
380,2017-06-08 23:55:00,2017,2017-06-08,23:55:00,2,3,11,18.333333,-7.333333
381,2017-06-09 00:00:00,2017,2017-06-09,00:00:00,2,2,7,17.500000,-10.500000
382,2017-06-09 00:05:00,2017,2017-06-09,00:05:00,1,2,7,17.500000,-10.500000
383,2017-06-09 00:10:00,2017,2017-06-09,00:10:00,2,2,7,17.500000,-10.500000
384,2017-06-09 00:15:00,2017,2017-06-09,00:15:00,2,2,7,17.500000,-10.500000
385,2017-06-09 00:20:00,2017,2017-06-09,00:20:00,2,2,8,20.000000,-12.000000
386,2017-06-09 00:25:00,2017,2017-06-09,00:25:00,2,2,8,20.000000,-12.000000
387,2017-06-09 00:30:00,2017,2017-06-09,00:30:00,1,1,5,25.000000,-20.000000
388,2017-06-09 00:35:00,2017,2017-06-09,00:35:00,1,2,6,15.000000,-9.000000
389,2017-06-09 00:40:00,2017,2017-06-09,00:40:00,1,1,5,25.000000,-20.000000
390,2017-06-09 00:45:00,2017,2017-06-09,00:45:00,1,1,5,25.000000,-20.000000
391,2017-06-09 00:50:00,2017,2017-06-09,00:50:00,1,2,6,15.000000,-9.000000
392,2017-06-09 00:55:00,2017,2017-06-09,00:55:00,1,1,5,25.000000,-20.000000
393,2017-06-09 01:00:00,2017,2017-06-09,01:00:00,1,1,5,25.000000,-20.000000
394,2017-06-09 01:05:00,2017,2017-06-09,01:05:00,1,1,5,25.000000,-20.000000
395,2017-06-09 01:10:00,2017,2017-06-09,01:10:00,1,2,7,17.500000,-10.500000
396,2017-06-09 01:15:00,2017,2017-06-09,01:15:00,1,2,6,15.000000,-9.000000
397,2017-06-09 01:20:00,2017,2017-06-09,01:20:00,1,1,4,20.000000,-16.000000
398,2017-06-09 01:25:00,2017,2017-06-09,01:25:00,1,2,6,15.000000,-9.000000
399,2017-06-09 01:30:00,2017,2017-06-09,01:30:00,1,2,6,15.000000,-9.000000

In [35]:
df = df.set_index('dt')

In [36]:
df.head()

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0,0.0
2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0,0.0
2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0,0.0
2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0,0.0
2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0,0.0

In [37]:
df.index = pd.DatetimeIndex(df.index)

In [38]:
df.head()

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0,0.0
2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0,0.0
2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0,0.0
2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0,0.0
2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0,0.0

In [39]:
# df.dt = pd.to_datetime(df.dt)

In [40]:
df[df['passengers_waiting'] < 0] = 0

In [41]:
df

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:05:00,2017,2017-06-07,16:05:00,0,0,0,0.0,0.0
2017-06-07 16:10:00,2017,2017-06-07,16:10:00,0,0,0,0.0,0.0
2017-06-07 16:15:00,2017,2017-06-07,16:15:00,0,0,0,0.0,0.0
2017-06-07 16:20:00,2017,2017-06-07,16:20:00,0,0,0,0.0,0.0
2017-06-07 16:25:00,2017,2017-06-07,16:25:00,0,0,0,0.0,0.0
2017-06-07 16:30:00,2017,2017-06-07,16:30:00,0,0,0,0.0,0.0
2017-06-07 16:35:00,2017,2017-06-07,16:35:00,0,0,0,0.0,0.0
2017-06-07 16:40:00,2017,2017-06-07,16:40:00,0,0,0,0.0,0.0
2017-06-07 16:45:00,2017,2017-06-07,16:45:00,0,0,0,0.0,0.0
2017-06-07 16:50:00,2017,2017-06-07,16:50:00,0,0,0,0.0,0.0
2017-06-07 16:55:00,2017,2017-06-07,16:55:00,0,0,0,0.0,0.0
2017-06-07 17:00:00,2017,2017-06-07,17:00:00,0,0,0,0.0,0.0
2017-06-07 17:05:00,2017,2017-06-07,17:05:00,0,0,0,0.0,0.0
2017-06-07 17:10:00,2017,2017-06-07,17:10:00,0,0,0,0.0,0.0
2017-06-07 17:15:00,2017,2017-06-07,17:15:00,0,0,0,0.0,0.0
2017-06-07 17:20:00,2017,2017-06-07,17:20:00,0,0,0,0.0,0.0
2017-06-07 17:25:00,2017,2017-06-07,17:25:00,0,0,0,0.0,0.0
2017-06-07 17:30:00,2017,2017-06-07,17:30:00,0,0,0,0.0,0.0
2017-06-07 17:35:00,2017,2017-06-07,17:35:00,0,0,0,0.0,0.0
2017-06-07 17:40:00,2017,2017-06-07,17:40:00,0,0,0,0.0,0.0
2017-06-07 17:45:00,2017,2017-06-07,17:45:00,0,0,0,0.0,0.0
2017-06-07 17:50:00,2017,2017-06-07,17:50:00,0,0,0,0.0,0.0
2017-06-07 17:55:00,2017,2017-06-07,17:55:00,0,0,0,0.0,0.0
2017-06-07 18:10:00,2017,2017-06-07,18:10:00,0,0,0,0.0,0.0
2017-06-07 18:15:00,2017,2017-06-07,18:15:00,0,0,0,0.0,0.0
2017-06-07 18:20:00,2017,2017-06-07,18:20:00,0,0,0,0.0,0.0
2017-06-07 18:25:00,2017,2017-06-07,18:25:00,0,0,0,0.0,0.0
2017-06-07 18:30:00,2017,2017-06-07,18:30:00,0,0,0,0.0,0.0
2017-06-07 18:35:00,2017,2017-06-07,18:35:00,0,0,0,0.0,0.0
2017-06-07 18:40:00,2017,2017-06-07,18:40:00,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...
2017-09-19 22:30:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 22:35:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 22:40:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 22:45:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 22:50:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 22:55:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:00:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:05:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:10:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:15:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:20:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:25:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:30:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:35:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:40:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:45:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:50:00,0,0,0,0,0,0,0.0,0.0
2017-09-19 23:55:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:00:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:05:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:10:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:15:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:20:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:25:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:30:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:35:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:40:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:45:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:50:00,0,0,0,0,0,0,0.0,0.0
2017-09-20 00:55:00,0,0,0,0,0,0,0.0,0.0

In [42]:
df = df.resample('1H').last()

In [43]:
df

,CalendarYear,Day,Time,Avg Total Time,Max Total Time,Max # of PAX in Line,PAX_through,passengers_waiting
dt,,,,,,,,
2017-06-07 16:00:00,2017.0,2017-06-07,16:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 17:00:00,2017.0,2017-06-07,17:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 18:00:00,2017.0,2017-06-07,18:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 19:00:00,2017.0,2017-06-07,19:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 20:00:00,2017.0,2017-06-07,20:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 21:00:00,2017.0,2017-06-07,21:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 22:00:00,2017.0,2017-06-07,22:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-07 23:00:00,2017.0,2017-06-07,23:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 00:00:00,2017.0,2017-06-08,00:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 01:00:00,2017.0,2017-06-08,01:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 02:00:00,2017.0,2017-06-08,02:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 03:00:00,2017.0,2017-06-08,03:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 04:00:00,2017.0,2017-06-08,04:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 05:00:00,2017.0,2017-06-08,05:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 06:00:00,2017.0,2017-06-08,06:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 07:00:00,2017.0,2017-06-08,07:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 08:00:00,2017.0,2017-06-08,08:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 09:00:00,2017.0,2017-06-08,09:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 10:00:00,2017.0,2017-06-08,10:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 11:00:00,2017.0,2017-06-08,11:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 12:00:00,2017.0,2017-06-08,12:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 13:00:00,2017.0,2017-06-08,13:55:00,0.0,0.0,0.0,0.000000,0.000000
2017-06-08 14:00:00,2017.0,2017-06-08,14:55:00,9.0,13.0,69.0,26.538462,42.461538
2017-06-08 15:00:00,2017.0,2017-06-08,15:55:00,9.0,10.0,53.0,26.500000,26.500000
2017-06-08 16:00:00,2017.0,2017-06-08,16:55:00,9.0,11.0,62.0,28.181818,33.818182
2017-06-08 17:00:00,2017.0,2017-06-08,17:55:00,15.0,16.0,84.0,26.250000,57.750000
2017-06-08 18:00:00,2017.0,2017-06-08,18:55:00,3.0,6.0,34.0,28.333333,5.666667
2017-06-08 19:00:00,2017.0,2017-06-08,19:55:00,11.0,14.0,78.0,27.857143,50.142857
2017-06-08 20:00:00,2017.0,2017-06-08,20:55:00,11.0,12.0,68.0,28.333333,39.666667
2017-06-08 21:00:00,2017.0,2017-06-08,21:55:00,10.0,12.0,66.0,27.500000,38.500000
...,...,...,...,...,...,...,...,...
2017-09-18 19:00:00,2017.0,2017-09-18,19:55:00,8.0,8.0,48.0,30.000000,18.000000
2017-09-18 20:00:00,2017.0,2017-09-18,20:55:00,11.0,14.0,77.0,27.500000,49.500000
2017-09-18 21:00:00,2017.0,2017-09-18,21:55:00,6.0,7.0,40.0,28.571429,11.428571
2017-09-18 22:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-18 23:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 00:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 01:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 02:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 03:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 04:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 05:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 06:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 07:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 08:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 09:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 10:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 11:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 12:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 13:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 14:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 15:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 16:00:00,2017.0,2017-09-19,16:55:00,4.0,5.0,25.0,25.000000,0.000000
2017-09-19 17:00:00,2017.0,2017-09-19,17:55:00,11.0,12.0,41.0,17.083333,23.916667
2017-09-19 18:00:00,2017.0,2017-09-19,18:55:00,6.0,7.0,37.0,26.428571,10.571429
2017-09-19 19:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 20:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 21:00:00,2017.0,2017-09-19,21:55:00,13.0,15.0,79.0,26.333333,52.666667
2017-09-19 22:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-19 23:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000
2017-09-20 00:00:00,0.0,0,0,0.0,0.0,0.0,0.000000,0.000000

In [44]:
out = df.groupby([df.index.hour])[["passengers_waiting"]].mean()

In [48]:
out

    passengers_waiting
dt
0            14.499131
1             2.896687
2             0.043956
3             0.000000
4             0.000000
5             0.017628
6             0.057692
7             0.205815
8             3.191694
9            11.693373
10           17.297022
11           24.594192
12            9.810684
13           12.861285
14           13.206582
15           27.196431
16           41.109798
17           38.588917
18           18.398089
19           22.920965
20           26.738826
21           35.564316
22           23.478536
23           29.787771

In [50]:
out.to_csv('../../clean_data/biases_per_hour.csv')