### Import Statements

In [1]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, Normalizer
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Activation
from keras.wrappers.scikit_learn import KerasRegressor

import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

%matplotlib inline
# plt.style.use("ggplot")
sns.set_style("darkgrid")

Using TensorFlow backend.

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

### Read the Data

In [3]:
data = pd.read_csv("../clean_data/FinalData_for_Models.csv")

In [4]:
data.rename(columns={'Unnamed: 0':'pickup_time'}, inplace=True)

In [5]:
data.head()

,pickup_time,num_pickups,num_passengers,missing_dt,temp,temp_min,temp_max,humidity,wind_speed,weather_main,weather_description,Passengers,Month,Hour,Day,holiday,precip_in,Avg_Delay_Arriving,Avg_Delay_Departing,Cancelled_Arriving_Flights,Cancelled_Departing_Flights
0,2014-01-01 00:00:00-05:00,107.0,210.0,False,269.27,267.59,270.93,80.0,3.0,clear,sky is clear,108.0,1,0,2,True,0.0,0.0,0.0,0.0,0.0
1,2014-01-01 01:00:00-05:00,34.0,45.0,False,268.90,267.04,270.93,80.0,2.0,clear,sky is clear,0.0,1,1,2,True,0.0,0.0,0.0,0.0,0.0
2,2014-01-01 02:00:00-05:00,34.0,70.0,False,268.48,266.48,270.37,57.0,3.0,clear,sky is clear,0.0,1,2,2,True,0.0,0.0,0.0,0.0,0.0
3,2014-01-01 03:00:00-05:00,12.0,18.0,False,268.33,265.93,270.37,80.0,3.0,clear,sky is clear,0.0,1,3,2,True,0.0,291.0,0.0,0.0,0.0
4,2014-01-01 04:00:00-05:00,25.0,37.0,False,268.10,265.37,270.37,80.0,3.0,clear,sky is clear,0.0,1,4,2,True,0.0,0.0,0.0,0.0,0.0

In [6]:
## ignoring the missing data values in 2016
data = data.loc[data.missing_dt == False, :]
data.drop("missing_dt", axis=1, inplace=True)

In [7]:
data.shape

(30647, 20)

### Creating Dummies for Weather Data

In [8]:
## for weather main
data_wm_dummies = data['weather_main'].str.split(",").str.join("*").str.get_dummies(sep='*')

In [9]:
## for weather description
data_wd_dummies = data['weather_description'].str.split(",").str.join("*").str.get_dummies(sep='*')

In [10]:
data.drop(["weather_main", "weather_description"], axis=1, inplace=True)

In [11]:
data = pd.concat([data, data_wm_dummies], axis=1)

In [12]:
data.shape

(30647, 24)

In [13]:
data.head()

,pickup_time,num_pickups,num_passengers,temp,temp_min,temp_max,humidity,wind_speed,Passengers,Month,Hour,Day,holiday,precip_in,Avg_Delay_Arriving,Avg_Delay_Departing,Cancelled_Arriving_Flights,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
0,2014-01-01 00:00:00-05:00,107.0,210.0,269.27,267.59,270.93,80.0,3.0,108.0,1,0,2,True,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1,2014-01-01 01:00:00-05:00,34.0,45.0,268.90,267.04,270.93,80.0,2.0,0.0,1,1,2,True,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
2,2014-01-01 02:00:00-05:00,34.0,70.0,268.48,266.48,270.37,57.0,3.0,0.0,1,2,2,True,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
3,2014-01-01 03:00:00-05:00,12.0,18.0,268.33,265.93,270.37,80.0,3.0,0.0,1,3,2,True,0.0,291.0,0.0,0.0,0.0,1,0,0,0,0,0
4,2014-01-01 04:00:00-05:00,25.0,37.0,268.10,265.37,270.37,80.0,3.0,0.0,1,4,2,True,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0

** Remark : We can choose to only include weather main categories or weather description also alongwith <br> TRY BOTH OF THEM FOR MODELS **

### Modifying Boolean Data Columns (Holiday)

In [14]:
data['holiday'] = data.holiday.astype(int)

In [15]:
data.head()

,pickup_time,num_pickups,num_passengers,temp,temp_min,temp_max,humidity,wind_speed,Passengers,Month,Hour,Day,holiday,precip_in,Avg_Delay_Arriving,Avg_Delay_Departing,Cancelled_Arriving_Flights,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
0,2014-01-01 00:00:00-05:00,107.0,210.0,269.27,267.59,270.93,80.0,3.0,108.0,1,0,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1,2014-01-01 01:00:00-05:00,34.0,45.0,268.90,267.04,270.93,80.0,2.0,0.0,1,1,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
2,2014-01-01 02:00:00-05:00,34.0,70.0,268.48,266.48,270.37,57.0,3.0,0.0,1,2,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
3,2014-01-01 03:00:00-05:00,12.0,18.0,268.33,265.93,270.37,80.0,3.0,0.0,1,3,2,1,0.0,291.0,0.0,0.0,0.0,1,0,0,0,0,0
4,2014-01-01 04:00:00-05:00,25.0,37.0,268.10,265.37,270.37,80.0,3.0,0.0,1,4,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0

### Time Feature

In [16]:
data.rename(columns={'Hour':'HourOfDay'}, inplace=True)
data.rename(columns={'Day':'DayOfWeek'}, inplace=True)

In [17]:
data.head(2)

,pickup_time,num_pickups,num_passengers,temp,temp_min,temp_max,humidity,wind_speed,Passengers,Month,HourOfDay,DayOfWeek,holiday,precip_in,Avg_Delay_Arriving,Avg_Delay_Departing,Cancelled_Arriving_Flights,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
0,2014-01-01 00:00:00-05:00,107.0,210.0,269.27,267.59,270.93,80.0,3.0,108.0,1,0,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1,2014-01-01 01:00:00-05:00,34.0,45.0,268.90,267.04,270.93,80.0,2.0,0.0,1,1,2,1,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0

In [18]:
data.shape

(30647, 24)

### Drop the Number of Passengers

In [19]:
data.drop(["num_passengers"], axis=1, inplace=True)

### Dropping cancelled arriving flights as they should have no influence in pickups at LGA

In [20]:
## as they will probably have no predictive value
data.drop(['Cancelled_Arriving_Flights'], axis=1, inplace=True)

In [21]:
data.drop(['Avg_Delay_Departing'], axis=1, inplace=True)

### Dropping Temp_Mix and Temp_Max as we already have Temp

In [22]:
data.drop(['temp_min', 'temp_max'], axis=1, inplace=True)

In [23]:
data.head()

,pickup_time,num_pickups,temp,humidity,wind_speed,Passengers,Month,HourOfDay,DayOfWeek,holiday,precip_in,Avg_Delay_Arriving,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
0,2014-01-01 00:00:00-05:00,107.0,269.27,80.0,3.0,108.0,1,0,2,1,0.0,0.0,0.0,1,0,0,0,0,0
1,2014-01-01 01:00:00-05:00,34.0,268.90,80.0,2.0,0.0,1,1,2,1,0.0,0.0,0.0,1,0,0,0,0,0
2,2014-01-01 02:00:00-05:00,34.0,268.48,57.0,3.0,0.0,1,2,2,1,0.0,0.0,0.0,1,0,0,0,0,0
3,2014-01-01 03:00:00-05:00,12.0,268.33,80.0,3.0,0.0,1,3,2,1,0.0,291.0,0.0,1,0,0,0,0,0
4,2014-01-01 04:00:00-05:00,25.0,268.10,80.0,3.0,0.0,1,4,2,1,0.0,0.0,0.0,1,0,0,0,0,0

### Dropping Month, HourOfDay, DayOfWeek

In [24]:
data.drop(['Month', 'HourOfDay', 'DayOfWeek'], axis=1, inplace=True)

In [25]:
data.head()

,pickup_time,num_pickups,temp,humidity,wind_speed,Passengers,holiday,precip_in,Avg_Delay_Arriving,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
0,2014-01-01 00:00:00-05:00,107.0,269.27,80.0,3.0,108.0,1,0.0,0.0,0.0,1,0,0,0,0,0
1,2014-01-01 01:00:00-05:00,34.0,268.90,80.0,2.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0
2,2014-01-01 02:00:00-05:00,34.0,268.48,57.0,3.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0
3,2014-01-01 03:00:00-05:00,12.0,268.33,80.0,3.0,0.0,1,0.0,291.0,0.0,1,0,0,0,0,0
4,2014-01-01 04:00:00-05:00,25.0,268.10,80.0,3.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0

In [26]:
data.set_index("pickup_time", inplace=True)

## LSTM models start from here

In [27]:
data.head()

,num_pickups,temp,humidity,wind_speed,Passengers,holiday,precip_in,Avg_Delay_Arriving,Cancelled_Departing_Flights,clear,clouds,fog,rain,snow,thunderstorm
pickup_time,,,,,,,,,,,,,,,
2014-01-01 00:00:00-05:00,107.0,269.27,80.0,3.0,108.0,1,0.0,0.0,0.0,1,0,0,0,0,0
2014-01-01 01:00:00-05:00,34.0,268.90,80.0,2.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0
2014-01-01 02:00:00-05:00,34.0,268.48,57.0,3.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0
2014-01-01 03:00:00-05:00,12.0,268.33,80.0,3.0,0.0,1,0.0,291.0,0.0,1,0,0,0,0,0
2014-01-01 04:00:00-05:00,25.0,268.10,80.0,3.0,0.0,1,0.0,0.0,0.0,1,0,0,0,0,0

In [28]:
## the labels (num_pickups)
num_pickups = data.num_pickups
data.drop("num_pickups", axis=1, inplace=True)

## LSTM RNN with Keras

In [29]:
# fix random seed for reproducibility
np.random.seed(7)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(data, num_pickups, test_size=0.15, random_state=42)

In [31]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [32]:
X_test_scaled = scaler.transform(X_test)

In [33]:
# define base mode
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(14, input_dim=14, kernel_initializer = 'normal', activation='relu'))
    model.add(Dense(140, kernel_initializer = 'normal', activation='relu'))
    model.add(Dense(48, kernel_initializer = 'normal', activation='relu'))
    model.add(Dense(10, kernel_initializer = 'normal', activation='relu'))
    model.add(Dense(1, kernel_initializer = 'normal'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [34]:
estimator = KerasRegressor(build_fn=baseline_model, epochs=100, batch_size=16, verbose=1)

In [35]:
estimator.fit(X_train.values, y_train.values)

Epoch 1/100
26049/26049 [==============================] - 9s 343us/step - loss: 68859.5924
Epoch 2/100
26049/26049 [==============================] - 8s 304us/step - loss: 61013.0670
Epoch 3/100
26049/26049 [==============================] - 8s 306us/step - loss: 60799.2353
Epoch 4/100
26049/26049 [==============================] - 8s 309us/step - loss: 60690.3888
Epoch 5/100
26049/26049 [==============================] - 8s 320us/step - loss: 60025.3837
Epoch 6/100
26049/26049 [==============================] - 8s 301us/step - loss: 56486.9609
Epoch 7/100
26049/26049 [==============================] - 8s 308us/step - loss: 55038.8680
Epoch 8/100
26049/26049 [==============================] - 9s 337us/step - loss: 54944.0987
Epoch 9/100
26049/26049 [==============================] - 8s 308us/step - loss: 54681.7342
Epoch 10/100
26049/26049 [==============================] - 8s 310us/step - loss: 54630.8081
Epoch 11/100
26049/26049 [==============================] - 8s 294us/step - loss: 53612.8382
Epoch 12/100
26049/26049 [==============================] - 8s 295us/step - loss: 47670.3687
Epoch 13/100
26049/26049 [==============================] - 8s 303us/step - loss: 40731.7952
Epoch 14/100
26049/26049 [==============================] - 8s 315us/step - loss: 36440.7132
Epoch 15/100
26049/26049 [==============================] - 9s 334us/step - loss: 34492.3696
Epoch 16/100
26049/26049 [==============================] - 8s 310us/step - loss: 33241.9367
Epoch 17/100
26049/26049 [==============================] - 8s 290us/step - loss: 32243.7724
Epoch 18/100
26049/26049 [==============================] - 8s 302us/step - loss: 31595.0967
Epoch 19/100
26049/26049 [==============================] - 8s 302us/step - loss: 31212.0303
Epoch 20/100
26049/26049 [==============================] - 8s 308us/step - loss: 31167.5134
Epoch 21/100
26049/26049 [==============================] - 8s 312us/step - loss: 30662.9924
Epoch 22/100
26049/26049 [==============================] - 8s 316us/step - loss: 30525.9289
Epoch 23/100
26049/26049 [==============================] - 9s 340us/step - loss: 30289.0702
Epoch 24/100
26049/26049 [==============================] - 8s 319us/step - loss: 30153.2647
Epoch 25/100
26049/26049 [==============================] - 8s 308us/step - loss: 30170.9406
Epoch 26/100
26049/26049 [==============================] - 8s 321us/step - loss: 29763.4194
Epoch 27/100
26049/26049 [==============================] - 8s 318us/step - loss: 29800.0188
Epoch 28/100
26049/26049 [==============================] - 8s 323us/step - loss: 29712.2876
Epoch 29/100
26049/26049 [==============================] - 8s 320us/step - loss: 29805.0948
Epoch 30/100
26049/26049 [==============================] - 8s 322us/step - loss: 29609.6763
Epoch 31/100
26049/26049 [==============================] - 8s 304us/step - loss: 29676.9936
Epoch 32/100
26049/26049 [==============================] - 8s 310us/step - loss: 29487.5367
Epoch 33/100
26049/26049 [==============================] - 8s 325us/step - loss: 29511.2789
Epoch 34/100
26049/26049 [==============================] - 8s 307us/step - loss: 29298.6925
Epoch 35/100
26049/26049 [==============================] - 9s 330us/step - loss: 29132.4423
Epoch 36/100
26049/26049 [==============================] - 8s 312us/step - loss: 29379.1552
Epoch 37/100
26049/26049 [==============================] - 8s 324us/step - loss: 29249.1489
Epoch 38/100
26049/26049 [==============================] - 8s 299us/step - loss: 29043.8738
Epoch 39/100
26049/26049 [==============================] - 8s 297us/step - loss: 29217.4284
Epoch 40/100
26049/26049 [==============================] - 8s 309us/step - loss: 28960.7575
Epoch 41/100
26049/26049 [==============================] - 8s 302us/step - loss: 29218.7212
Epoch 42/100
26049/26049 [==============================] - 8s 309us/step - loss: 28933.2396
Epoch 43/100
26049/26049 [==============================] - 8s 318us/step - loss: 29064.9285
Epoch 44/100
26049/26049 [==============================] - 8s 321us/step - loss: 28733.4794
Epoch 45/100
26049/26049 [==============================] - 9s 331us/step - loss: 28731.0593
Epoch 46/100
26049/26049 [==============================] - 8s 309us/step - loss: 28818.0298
Epoch 47/100
26049/26049 [==============================] - 8s 307us/step - loss: 28692.1735
Epoch 48/100
26049/26049 [==============================] - 8s 301us/step - loss: 28842.7812
Epoch 49/100
26049/26049 [==============================] - 8s 316us/step - loss: 28711.7876
Epoch 50/100
26049/26049 [==============================] - 8s 293us/step - loss: 28694.5754
Epoch 51/100
26049/26049 [==============================] - 8s 302us/step - loss: 28567.3967
Epoch 52/100
26049/26049 [==============================] - 8s 321us/step - loss: 28645.7269
Epoch 53/100
26049/26049 [==============================] - 8s 301us/step - loss: 28711.0173
Epoch 54/100
26049/26049 [==============================] - 8s 300us/step - loss: 28617.5771
Epoch 55/100
26049/26049 [==============================] - 8s 290us/step - loss: 28664.6591
Epoch 56/100
26049/26049 [==============================] - 8s 304us/step - loss: 28421.7176
Epoch 57/100
26049/26049 [==============================] - 8s 321us/step - loss: 28467.0460
Epoch 58/100
26049/26049 [==============================] - 9s 326us/step - loss: 28663.3396
Epoch 59/100
26049/26049 [==============================] - 8s 304us/step - loss: 28449.4595
Epoch 60/100
26049/26049 [==============================] - 8s 320us/step - loss: 28391.6192
Epoch 61/100
26049/26049 [==============================] - 8s 301us/step - loss: 28480.3910
Epoch 62/100
26049/26049 [==============================] - 8s 295us/step - loss: 28381.6030
Epoch 63/100
26049/26049 [==============================] - 8s 322us/step - loss: 28339.0167
Epoch 64/100
26049/26049 [==============================] - 8s 303us/step - loss: 28347.6906
Epoch 65/100
26049/26049 [==============================] - 8s 317us/step - loss: 28210.0290
Epoch 66/100
26049/26049 [==============================] - 8s 314us/step - loss: 28176.4079
Epoch 67/100
26049/26049 [==============================] - 8s 316us/step - loss: 28341.0031
Epoch 68/100
26049/26049 [==============================] - 8s 307us/step - loss: 28421.3487
Epoch 69/100
26049/26049 [==============================] - 8s 289us/step - loss: 28297.4082
Epoch 70/100
26049/26049 [==============================] - 8s 299us/step - loss: 28188.7297
Epoch 71/100
26049/26049 [==============================] - 8s 301us/step - loss: 28198.3115
Epoch 72/100
26049/26049 [==============================] - 8s 315us/step - loss: 28140.0932
Epoch 73/100
26049/26049 [==============================] - 8s 297us/step - loss: 28121.4202
Epoch 74/100
26049/26049 [==============================] - 8s 299us/step - loss: 28199.5706
Epoch 75/100
26049/26049 [==============================] - 8s 307us/step - loss: 28314.4394
Epoch 76/100
26049/26049 [==============================] - 8s 310us/step - loss: 28013.4001
Epoch 77/100
26049/26049 [==============================] - 8s 306us/step - loss: 28216.5205
Epoch 78/100
26049/26049 [==============================] - 8s 303us/step - loss: 28069.7640
Epoch 79/100
26049/26049 [==============================] - 8s 307us/step - loss: 28194.5574
Epoch 80/100
26049/26049 [==============================] - 8s 297us/step - loss: 28059.7852
Epoch 81/100
26049/26049 [==============================] - 8s 300us/step - loss: 28175.5883
Epoch 82/100
26049/26049 [==============================] - 8s 307us/step - loss: 28206.1665
Epoch 83/100
26049/26049 [==============================] - 8s 301us/step - loss: 28047.5054
Epoch 84/100
26049/26049 [==============================] - 8s 294us/step - loss: 28223.6453
Epoch 85/100
26049/26049 [==============================] - 8s 306us/step - loss: 27989.3976
Epoch 86/100
26049/26049 [==============================] - 8s 293us/step - loss: 28079.2190
Epoch 87/100
26049/26049 [==============================] - 8s 300us/step - loss: 27893.3642
Epoch 88/100
26049/26049 [==============================] - 8s 304us/step - loss: 27984.0534
Epoch 89/100

26049/26049 [==============================] - 8s 306us/step - loss: 28019.4365
Epoch 90/100
26049/26049 [==============================] - 9s 330us/step - loss: 27876.6479
Epoch 91/100
26049/26049 [==============================] - 8s 303us/step - loss: 27839.7150
Epoch 92/100
26049/26049 [==============================] - 8s 302us/step - loss: 28149.4048
Epoch 93/100
26049/26049 [==============================] - 8s 306us/step - loss: 27821.5527
Epoch 94/100
26049/26049 [==============================] - 8s 304us/step - loss: 27954.2617
Epoch 95/100
26049/26049 [==============================] - 8s 316us/step - loss: 27918.6397
Epoch 96/100
26049/26049 [==============================] - 8s 317us/step - loss: 27861.9170
Epoch 97/100
26049/26049 [==============================] - 9s 332us/step - loss: 27769.1960
Epoch 98/100
26049/26049 [==============================] - 8s 314us/step - loss: 27868.0556
Epoch 99/100
26049/26049 [==============================] - 8s 311us/step - loss: 27797.8140
Epoch 100/100
26049/26049 [==============================] - 8s 312us/step - loss: 27732.4685

In [41]:
pred_y = estimator.predict(X_test.values)

4598/4598 [==============================] - 0s 53us/step

In [42]:
r2 = r2_score(y_test, pred_y)

In [43]:
r2

0.63811028563086825

In [44]:
rmse = mean_squared_error(y_test, pred_y )

In [45]:
print(rmse)

29311.2636123