## Merging hourly taxi, weather, and incoming passenger data for 2017

### Count of Taxi Pickups per hour

In [2]:
import numpy as np
from tqdm import tqdm
import pandas as pd
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

In [2]:
def taxi_resample(path):
    taxi_df = pd.read_csv(path, compression='gzip')
    taxi_df["tpep_pickup_datetime"] = pd.DatetimeIndex(taxi_df.tpep_pickup_datetime).tz_localize('America/New_York')
    taxi_df["tpep_dropoff_datetime"] = pd.DatetimeIndex(taxi_df.tpep_dropoff_datetime).tz_localize('America/New_York')
    taxi_df.set_index("tpep_pickup_datetime", inplace = True)
    taxi_hourly = taxi_df.resample('H')['passenger_count'].count()
    taxi_hourly_df = taxi_hourly.to_frame()
    taxi_hourly_df.rename(columns={'passenger_count':'pickup_count'}, inplace = True)
    return taxi_hourly_df

In [3]:
taxi_hourly_df = taxi_resample('../clean_data/TaxiData_Jan17-Jun17.gz')

### Weather Data

In [3]:
check = pd.read_csv("../clean_data/weather_NY.csv")

In [4]:
check.head()

,dt,dt_iso,city_id,city_name,lat,lon,temp,temp_min,temp_max,pressure,...,rain_today,snow_1h,snow_3h,snow_24h,snow_today,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,1349096400,2012-10-01 13:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.22,286.15,294.26,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
1,1349186400,2012-10-02 14:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.15,288.15,294.82,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
2,1349190000,2012-10-02 15:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.32,289.82,296.48,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
3,1349193600,2012-10-02 16:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.78,290.15,295.93,0,...,0.0,NaN,NaN,NaN,NaN,92,800,Clear,sky is clear,02d
4,1349197200,2012-10-02 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,292.74,291.15,296.48,0,...,0.0,NaN,NaN,NaN,NaN,92,800,Clear,sky is clear,02d

In [8]:
check["date"] = pd.DatetimeIndex(pd.to_datetime(check.dt, unit="s")) \
                    .tz_localize('UTC').tz_convert('America/New_York')

In [10]:
check.set_index("date", inplace=True)

In [19]:
check

,dt,dt_iso,city_id,city_name,lat,lon,temp,temp_min,temp_max,pressure,...,rain_today,snow_1h,snow_3h,snow_24h,snow_today,clouds_all,weather_id,weather_main,weather_description,weather_icon
date,,,,,,,,,,,,,,,,,,,,,
2012-10-01 09:00:00-04:00,1349096400,2012-10-01 13:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.22,286.15,294.26,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
2012-10-02 10:00:00-04:00,1349186400,2012-10-02 14:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.15,288.15,294.82,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
2012-10-02 11:00:00-04:00,1349190000,2012-10-02 15:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.32,289.82,296.48,1012,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
2012-10-02 12:00:00-04:00,1349193600,2012-10-02 16:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.78,290.15,295.93,0,...,0.0,NaN,NaN,NaN,NaN,92,800,Clear,sky is clear,02d
2012-10-02 13:00:00-04:00,1349197200,2012-10-02 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,292.74,291.15,296.48,0,...,0.0,NaN,NaN,NaN,NaN,92,800,Clear,sky is clear,02d
2012-10-02 14:00:00-04:00,1349200800,2012-10-02 18:00:00 +0000 UTC,5128581,NaN,NaN,NaN,293.82,293.15,295.15,1011,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
2012-10-02 15:00:00-04:00,1349204400,2012-10-02 19:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.08,293.15,295.15,0,...,0.0,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,02d
2012-10-02 16:00:00-04:00,1349208000,2012-10-02 20:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.72,294.15,295.37,1012,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
2012-10-02 17:00:00-04:00,1349211600,2012-10-02 21:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.85,293.15,295.93,0,...,0.0,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,02d
2012-10-02 18:00:00-04:00,1349215200,2012-10-02 22:00:00 +0000 UTC,5128581,NaN,NaN,NaN,293.20,291.48,295.15,1012,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
2012-10-02 19:00:00-04:00,1349218800,2012-10-02 23:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.98,287.59,294.15,1013,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-02 20:00:00-04:00,1349222400,2012-10-03 00:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.84,286.15,294.15,1014,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-02 21:00:00-04:00,1349226000,2012-10-03 01:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.99,285.15,294.15,1014,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2012-10-02 22:00:00-04:00,1349229600,2012-10-03 02:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.80,285.15,294.15,1015,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-02 23:00:00-04:00,1349233200,2012-10-03 03:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.60,285.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-03 00:00:00-04:00,1349236800,2012-10-03 04:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.54,285.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-03 01:00:00-04:00,1349240400,2012-10-03 05:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.60,285.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04n
2012-10-03 02:00:00-04:00,1349244000,2012-10-03 06:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.85,286.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
2012-10-03 03:00:00-04:00,1349247600,2012-10-03 07:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.05,286.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04n
2012-10-03 04:00:00-04:00,1349251200,2012-10-03 08:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.17,287.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04n
2012-10-03 05:00:00-04:00,1349254800,2012-10-03 09:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.36,287.15,292.15,1015,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04n
2012-10-03 06:00:00-04:00,1349258400,2012-10-03 10:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.50,287.15,292.15,1016,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04n
2012-10-03 07:00:00-04:00,1349262000,2012-10-03 11:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.56,287.15,292.15,1016,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04d
2012-10-03 09:00:00-04:00,1349269200,2012-10-03 13:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.18,289.15,293.15,1017,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04d
2012-10-03 10:00:00-04:00,1349272800,2012-10-03 14:00:00 +0000 UTC,5128581,NaN,NaN,NaN,292.88,290.15,295.93,1017,...,NaN,NaN,NaN,NaN,NaN,90,804,Clouds,overcast clouds,04d
2012-10-03 13:00:00-04:00,1349283600,2012-10-03 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.03,289.15,292.59,1017,...,NaN,NaN,NaN,NaN,NaN,35,500,Rain,light rain,10d
2012-10-03 13:00:00-04:00,1349283600,2012-10-03 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.03,289.15,292.59,1017,...,NaN,NaN,NaN,NaN,NaN,35,501,Rain,moderate rain,10d
2012-10-03 13:00:00-04:00,1349283600,2012-10-03 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.03,289.15,292.59,1017,...,NaN,NaN,NaN,NaN,NaN,35,701,Mist,mist,50d
2012-10-03 14:00:00-04:00,1349287200,2012-10-03 18:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.70,289.15,292.59,1016,...,NaN,NaN,NaN,NaN,NaN,100,500,Rain,light rain,10d
2012-10-03 14:00:00-04:00,1349287200,2012-10-03 18:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.70,289.15,292.59,1016,...,NaN,NaN,NaN,NaN,NaN,100,701,Mist,mist,50d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-19 15:00:00-04:00,1508439600,2017-10-19 19:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.90,293.15,296.15,1021,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-19 16:00:00-04:00,1508443200,2017-10-19 20:00:00 +0000 UTC,5128581,NaN,NaN,NaN,295.24,294.15,296.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-19 17:00:00-04:00,1508446800,2017-10-19 21:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.65,292.15,297.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-19 18:00:00-04:00,1508450400,2017-10-19 22:00:00 +0000 UTC,5128581,NaN,NaN,NaN,292.48,291.15,294.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-19 19:00:00-04:00,1508454000,2017-10-19 23:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.45,286.15,294.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-19 20:00:00-04:00,1508457600,2017-10-20 00:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.67,284.15,293.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-19 21:00:00-04:00,1508461200,2017-10-20 01:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.30,284.15,292.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-19 22:00:00-04:00,1508464800,2017-10-20 02:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.23,283.15,292.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-19 23:00:00-04:00,1508468400,2017-10-20 03:00:00 +0000 UTC,5128581,NaN,NaN,NaN,287.28,281.15,291.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 00:00:00-04:00,1508472000,2017-10-20 04:00:00 +0000 UTC,5128581,NaN,NaN,NaN,286.59,281.15,291.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 01:00:00-04:00,1508475600,2017-10-20 05:00:00 +0000 UTC,5128581,NaN,NaN,NaN,286.52,281.15,292.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 02:00:00-04:00,1508479200,2017-10-20 06:00:00 +0000 UTC,5128581,NaN,NaN,NaN,286.13,280.15,291.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 03:00:00-04:00,1508482800,2017-10-20 07:00:00 +0000 UTC,5128581,NaN,NaN,NaN,285.67,279.15,291.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 04:00:00-04:00,1508486400,2017-10-20 08:00:00 +0000 UTC,5128581,NaN,NaN,NaN,285.13,279.15,291.15,1019,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 05:00:00-04:00,1508490000,2017-10-20 09:00:00 +0000 UTC,5128581,NaN,NaN,NaN,284.52,279.15,290.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,701,Mist,mist,50n
2017-10-20 06:00:00-04:00,1508493600,2017-10-20 10:00:00 +0000 UTC,5128581,NaN,NaN,NaN,284.44,278.15,291.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,701,Mist,mist,50n
2017-10-20 07:00:00-04:00,1508497200,2017-10-20 11:00:00 +0000 UTC,5128581,NaN,NaN,NaN,283.75,277.15,290.15,1021,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 08:00:00-04:00,1508500800,2017-10-20 12:00:00 +0000 UTC,5128581,NaN,NaN,NaN,285.80,279.15,290.15,1022,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 09:00:00-04:00,1508504400,2017-10-20 13:00:00 +0000 UTC,5128581,NaN,NaN,NaN,288.06,283.15,291.15,1022,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 10:00:00-04:00,1508508000,2017-10-20 14:00:00 +0000 UTC,5128581,NaN,NaN,NaN,290.38,289.15,291.15,1023,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 11:00:00-04:00,1508511600,2017-10-20 15:00:00 +0000 UTC,5128581,NaN,NaN,NaN,291.91,290.15,293.15,1022,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 12:00:00-04:00,1508515200,2017-10-20 16:00:00 +0000 UTC,5128581,NaN,NaN,NaN,293.61,292.15,295.15,1022,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 13:00:00-04:00,1508518800,2017-10-20 17:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.69,293.15,296.15,1021,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 14:00:00-04:00,1508522400,2017-10-20 18:00:00 +0000 UTC,5128581,NaN,NaN,NaN,295.40,294.15,296.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,721,Haze,haze,50d
2017-10-20 15:00:00-04:00,1508526000,2017-10-20 19:00:00 +0000 UTC,5128581,NaN,NaN,NaN,296.15,295.15,297.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,721,Haze,haze,50d
2017-10-20 16:00:00-04:00,1508529600,2017-10-20 20:00:00 +0000 UTC,5128581,NaN,NaN,NaN,296.30,295.15,297.15,1020,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 17:00:00-04:00,1508533200,2017-10-20 21:00:00 +0000 UTC,5128581,NaN,NaN,NaN,295.82,295.15,296.15,1019,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
2017-10-20 18:00:00-04:00,1508536800,2017-10-20 22:00:00 +0000 UTC,5128581,NaN,NaN,NaN,294.14,291.15,296.15,1021,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01d
2017-10-20 19:00:00-04:00,1508540400,2017-10-20 23:00:00 +0000 UTC,5128581,NaN,NaN,NaN,292.23,289.15,295.15,1021,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n
2017-10-20 20:00:00-04:00,1508544000,2017-10-21 00:00:00 +0000 UTC,5128581,NaN,NaN,NaN,289.51,284.15,294.15,1022,...,NaN,NaN,NaN,NaN,NaN,1,800,Clear,sky is clear,01n

In [4]:
def clean_weather(path):
    weather_df = pd.read_csv(path)
    weather_df["date"] = pd.DatetimeIndex(pd.to_datetime(weather_df.dt, unit="s")) \
                    .tz_localize('UTC').tz_convert('America/New_York')
    weather_df.drop_duplicates(['date'], keep='first', inplace = True)
    weather_df.set_index("date", inplace=True)
    
    weather_df.drop(["dt", "dt_iso", "city_id", "city_name", "lat", "lon", "weather_icon", "grnd_level", \
                 "sea_level", "clouds_all", "weather_id", "rain_1h", "rain_3h", "rain_24h", \
                 "rain_today", "snow_1h", "snow_3h", "snow_24h", "snow_today"], axis=1, inplace=True)
    return weather_df

In [5]:
weather_df = clean_weather("../clean_data/weather_NY.csv")

### Merge Taxi and Weather Data

In [6]:
taxi_weather = taxi_hourly_df.merge(right=weather_df, how='left', left_index=True, right_index=True)
taxi_weather.index = taxi_weather.index.tz_convert('America/New_York')

In [7]:
taxi_weather_filled = taxi_weather.fillna(method='ffill')

In [8]:
taxi_weather_filled.head()

,pickup_count,temp,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,weather_main,weather_description
tpep_pickup_datetime,,,,,,,,,,
2017-01-01 00:00:00-05:00,53,279.07,277.15,280.15,1013.0,45.0,2.0,250.0,Clouds,overcast clouds
2017-01-01 01:00:00-05:00,3,279.14,277.15,281.15,1013.0,45.0,2.0,260.0,Clouds,overcast clouds
2017-01-01 02:00:00-05:00,0,279.21,276.15,283.15,1012.0,45.0,3.0,270.0,Rain,light rain
2017-01-01 03:00:00-05:00,4,279.43,277.15,285.15,1013.0,45.0,3.0,270.0,Clouds,overcast clouds
2017-01-01 04:00:00-05:00,4,279.50,276.15,286.15,1014.0,42.0,4.0,280.0,Clouds,scattered clouds

### Passenger seat data

In [9]:
def clean_seats(path):
    seats_per_hour = pd.read_csv(path, header=None)
#     print(seats_per_hour.head())
    seats_per_hour.columns = ['Time', 'Passengers']
    seats_per_hour["Time"] = pd.DatetimeIndex(seats_per_hour.Time)
    seats_per_hour.set_index("Time", inplace = True)

    #To get rid of errors surrounding daylight savings time. All of taxi pickups and passenger counts are NaNs for these times
    seats_per_hour = seats_per_hour.drop([pd.Timestamp('2016-03-13 02:00:00'), pd.Timestamp('2016-11-06 01:00:00'), pd.Timestamp('2017-03-12 02:00:00')])
    seats_per_hour.index = seats_per_hour.index.tz_localize('America/New_York')
    return seats_per_hour

In [10]:
seats_per_hour = clean_seats("../clean_data/seats_per_hour.csv")

### Merging all dataframes

In [11]:
merged_df = pd.merge(left=taxi_weather_filled, right=seats_per_hour, how='inner', left_index=True, right_index=True)

In [12]:
merged_df.head(20)

,pickup_count,temp,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,weather_main,weather_description,Passengers
2017-01-01 00:00:00-05:00,53,279.07,277.15,280.15,1013.0,45.0,2.0,250.0,Clouds,overcast clouds,NaN
2017-01-01 01:00:00-05:00,3,279.14,277.15,281.15,1013.0,45.0,2.0,260.0,Clouds,overcast clouds,150.0
2017-01-01 02:00:00-05:00,0,279.21,276.15,283.15,1012.0,45.0,3.0,270.0,Rain,light rain,NaN
2017-01-01 03:00:00-05:00,4,279.43,277.15,285.15,1013.0,45.0,3.0,270.0,Clouds,overcast clouds,NaN
2017-01-01 04:00:00-05:00,4,279.50,276.15,286.15,1014.0,42.0,4.0,280.0,Clouds,scattered clouds,NaN
2017-01-01 05:00:00-05:00,6,279.21,276.15,286.15,1015.0,48.0,2.0,280.0,Clouds,overcast clouds,NaN
2017-01-01 06:00:00-05:00,4,278.80,276.15,286.15,1016.0,52.0,2.0,290.0,Clear,sky is clear,NaN
2017-01-01 07:00:00-05:00,35,277.84,275.15,281.15,1017.0,55.0,2.0,220.0,Clouds,scattered clouds,272.0
2017-01-01 08:00:00-05:00,101,277.30,274.15,281.15,1018.0,64.0,2.0,220.0,Clear,sky is clear,1130.0
2017-01-01 09:00:00-05:00,147,277.98,276.15,281.15,1020.0,48.0,2.0,220.0,Clouds,scattered clouds,564.0
2017-01-01 10:00:00-05:00,293,279.60,277.15,281.15,1021.0,48.0,4.0,320.0,Clouds,scattered clouds,1465.0
2017-01-01 11:00:00-05:00,250,280.45,278.15,281.15,1022.0,42.0,5.0,340.0,Clouds,scattered clouds,572.0
2017-01-01 12:00:00-05:00,260,280.76,279.15,282.15,1022.0,36.0,7.0,310.0,Clear,sky is clear,772.0
2017-01-01 13:00:00-05:00,296,281.22,279.15,282.15,1022.0,33.0,3.0,296.0,Clear,sky is clear,1475.0
2017-01-01 14:00:00-05:00,337,281.30,280.15,282.15,1023.0,31.0,3.0,296.0,Clear,sky is clear,1514.0
2017-01-01 15:00:00-05:00,383,281.61,280.15,283.15,1023.0,31.0,4.0,320.0,Clear,sky is clear,1774.0
2017-01-01 16:00:00-05:00,437,281.61,280.15,283.15,1025.0,31.0,2.0,350.0,Clear,sky is clear,1456.0
2017-01-01 17:00:00-05:00,525,280.84,279.15,282.15,1026.0,35.0,2.0,350.0,Clear,sky is clear,2033.0
2017-01-01 18:00:00-05:00,368,278.44,274.15,281.15,1027.0,64.0,1.0,310.0,Clear,sky is clear,780.0
2017-01-01 19:00:00-05:00,385,276.72,272.15,281.15,1028.0,74.0,1.0,310.0,Clear,sky is clear,1201.0

In [13]:
merged_df.to_csv("../clean_data/2017_combined_data.csv")